name: deploy

on:
  push:
    branches: [main]

jobs:
  'deploy':
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: |
          npm i -g pnpm
          pnpm i

      - name: Build react
        run: pnpm build

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
